#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 24, 2019 01:08:11 PM PST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global inputDiam
    inputDiam = tk.StringVar()
    global percStep
    percStep = tk.DoubleVar()
    global downStep
    downStep = tk.DoubleVar()
    global inputSfpm
    inputSfpm = tk.StringVar()
    global inputFlutes
    inputFlutes = tk.StringVar()
    global rpm
    rpm = tk.StringVar()
    global ipm
    ipm = tk.StringVar()
    global rctrpm
    rctrpm = tk.StringVar()
    global rctipm
    rctipm = tk.StringVar()
    global stepovar
    stepovar = tk.StringVar()
    global stepdvar
    stepdvar = tk.StringVar()

def calculate():
    rpm.set((float(inputSfpm.get()) * 3.82) / float(inputDiam.get()))   # calc RPM
    #print(rev)
    sys.stdout.flush()

def set_stepd(*args):
    print('BLACK_support.set_stepd')
    sys.stdout.flush()

def set_stepo(*args):
    print('BLACK_support.set_stepo')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import BLACK
    BLACK.vp_start_gui()




