#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 24, 2019 03:44:16 PM PST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SuperDuper_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    SuperDuper_support.set_Tk_var()
    top = Toplevel1 (root)
    SuperDuper_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    SuperDuper_support.set_Tk_var()
    top = Toplevel1 (w)
    SuperDuper_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#000000'  # X11 color: 'black'
        _fgcolor = '#838383'  # Closest X11 color: 'gray51'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("451x561+1038+133")
        top.minsize(292, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("Super Duper")
        top.iconbitmap('PURPYANG.ICO')
        top.configure(background="#4e0c69")
        top.configure(highlightbackground="#5c5c5c")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.024, rely=0.025, relheight=0.95, relwidth=0.951)

        self.Frame1.configure(relief='raised')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="raised")
        self.Frame1.configure(background="#000000")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.047, rely=0.038, height=21, width=54)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#000000")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#838383")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Diameter''')

        self.diam = tk.Entry(self.Frame1)
        self.diam.place(relx=0.093, rely=0.094,height=20, relwidth=0.147)
        self.diam.configure(background="#000000")
        self.diam.configure(disabledforeground="#a3a3a3")
        self.diam.configure(font="-family {Consolas} -size 10 -weight bold")
        self.diam.configure(foreground="#919191")
        self.diam.configure(highlightbackground="#4f4f4f")
        self.diam.configure(highlightcolor="black")
        self.diam.configure(insertbackground="#969696")
        self.diam.configure(justify='center')
        self.diam.configure(selectbackground="#d1d1d1")
        self.diam.configure(selectforeground="black")
        self.diam.configure(textvariable=SuperDuper_support.inputDiam)

        self.sfpm = tk.Entry(self.Frame1)
        self.sfpm.place(relx=0.093, rely=0.225,height=20, relwidth=0.147)
        self.sfpm.configure(background="#000000")
        self.sfpm.configure(disabledforeground="#a3a3a3")
        self.sfpm.configure(font="-family {Consolas} -size 10 -weight bold")
        self.sfpm.configure(foreground="#919191")
        self.sfpm.configure(highlightbackground="#4f4f4f")
        self.sfpm.configure(highlightcolor="black")
        self.sfpm.configure(insertbackground="#969696")
        self.sfpm.configure(justify='center')
        self.sfpm.configure(selectbackground="#d1d1d1")
        self.sfpm.configure(selectforeground="black")
        self.sfpm.configure(textvariable=SuperDuper_support.inputSfpm)

        self.flutes = tk.Entry(self.Frame1)
        self.flutes.place(relx=0.093, rely=0.356,height=20, relwidth=0.147)
        self.flutes.configure(background="#000000")
        self.flutes.configure(disabledforeground="#a3a3a3")
        self.flutes.configure(font="-family {Consolas} -size 10 -weight bold")
        self.flutes.configure(foreground="#919191")
        self.flutes.configure(highlightbackground="#4f4f4f")
        self.flutes.configure(highlightcolor="black")
        self.flutes.configure(insertbackground="#969696")
        self.flutes.configure(justify='center')
        self.flutes.configure(selectbackground="#d1d1d1")
        self.flutes.configure(selectforeground="black")
        self.flutes.configure(textvariable=SuperDuper_support.inputFlutes)

        self.flutes_3 = tk.Entry(self.Frame1)
        self.flutes_3.place(relx=0.093, rely=0.488,height=21, relwidth=0.147)
        self.flutes_3.configure(background="#000000")
        self.flutes_3.configure(disabledforeground="#a3a3a3")
        self.flutes_3.configure(font="-family {Consolas} -size 10 -weight bold")
        self.flutes_3.configure(foreground="#919191")
        self.flutes_3.configure(highlightbackground="#4f4f4f")
        self.flutes_3.configure(highlightcolor="black")
        self.flutes_3.configure(insertbackground="#969696")
        self.flutes_3.configure(justify='center')
        self.flutes_3.configure(selectbackground="#d1d1d1")
        self.flutes_3.configure(selectforeground="black")
        self.flutes_3.configure(textvariable=SuperDuper_support.inputIpt)

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.023, rely=0.169, height=21, width=54)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#000000")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#838383")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''SFPM''')

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.047, rely=0.3, height=21, width=64)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#000000")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#838383")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''# of Flutes''')

        self.stepo = tk.Scale(self.Frame1, from_=0.0, to=100.0)
        self.stepo.place(relx=0.07, rely=0.619, relwidth=0.247, relheight=0.0
                , height=42, bordermode='ignore')
        self.stepo.configure(activebackground="#690f96")
        self.stepo.configure(background="#000000")
        self.stepo.configure(command=SuperDuper_support.set_stepo)
        self.stepo.configure(foreground="#838383")
        self.stepo.configure(highlightbackground="#000000")
        self.stepo.configure(highlightcolor="black")
        self.stepo.configure(orient="horizontal")
        self.stepo.configure(troughcolor="#000000")
        self.stepo.configure(variable=SuperDuper_support.percStep)

        self.Label1_3 = tk.Label(self.Frame1)
        self.Label1_3.place(relx=0.047, rely=0.582, height=11, width=94)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#000000")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#838383")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Stepover % of D''')

        self.stepd = tk.Scale(self.Frame1, from_=0.0, to=10.0)
        self.stepd.place(relx=0.093, rely=0.769, relwidth=0.0, relheight=0.199
                , width=54, bordermode='ignore')
        self.stepd.configure(activebackground="#690f96")
        self.stepd.configure(background="#000000")
        self.stepd.configure(command=SuperDuper_support.set_stepd)
        self.stepd.configure(foreground="#838383")
        self.stepd.configure(highlightbackground="#000000")
        self.stepd.configure(highlightcolor="black")
        self.stepd.configure(resolution="0.01")
        self.stepd.configure(troughcolor="#000000")
        self.stepd.configure(variable=SuperDuper_support.downStep)

        self.Label1_4 = tk.Label(self.Frame1)
        self.Label1_4.place(relx=0.047, rely=0.732, height=11, width=74)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#000000")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#838383")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Stepdown x D''')

        self.calcbutton = tk.Button(self.Frame1)
        self.calcbutton.place(relx=0.559, rely=0.075, height=64, width=82)
        self.calcbutton.configure(activebackground="#690f96")
        self.calcbutton.configure(activeforeground="white")
        self.calcbutton.configure(activeforeground="#838383")
        self.calcbutton.configure(background="#000000")
        self.calcbutton.configure(command=SuperDuper_support.calculate)
        self.calcbutton.configure(disabledforeground="#a3a3a3")
        self.calcbutton.configure(foreground="#838383")
        self.calcbutton.configure(highlightbackground="#000000")
        self.calcbutton.configure(highlightcolor="black")
        self.calcbutton.configure(pady="0")
        self.calcbutton.configure(text='''Calculate''')

        self.output = tk.LabelFrame(self.Frame1)
        self.output.place(relx=0.443, rely=0.281, relheight=0.486
                , relwidth=0.443)
        self.output.configure(relief='groove')
        self.output.configure(foreground="#a0a0a0")
        self.output.configure(text='''Output''')
        self.output.configure(background="#000000")
        self.output.configure(highlightbackground="#d9d9d9")
        self.output.configure(highlightcolor="black")

        self.rpm = tk.Entry(self.output)
        self.rpm.place(relx=0.1, rely=0.193, height=19, relwidth=0.353
                , bordermode='ignore')
        self.rpm.configure(background="#000000")
        self.rpm.configure(disabledforeground="#a3a3a3")
        self.rpm.configure(font="-family {Consolas} -size 10 -weight bold")
        self.rpm.configure(foreground="#919191")
        self.rpm.configure(highlightbackground="#4f4f4f")
        self.rpm.configure(highlightcolor="black")
        self.rpm.configure(insertbackground="#969696")
        self.rpm.configure(justify='center')
        self.rpm.configure(selectbackground="#c4c4c4")
        self.rpm.configure(selectforeground="black")
        self.rpm.configure(textvariable=SuperDuper_support.rpm)

        self.Label2 = tk.Label(self.output)
        self.Label2.place(relx=0.1, rely=0.116, height=11, width=34
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#000000")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#838383")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''RPM''')

        self.Label2_7 = tk.Label(self.output)
        self.Label2_7.place(relx=0.1, rely=0.309, height=11, width=34
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(background="#000000")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(foreground="#838383")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(text='''IPM''')

        self.ipm = tk.Entry(self.output)
        self.ipm.place(relx=0.1, rely=0.386, height=19, relwidth=0.353
                , bordermode='ignore')
        self.ipm.configure(background="#000000")
        self.ipm.configure(disabledforeground="#a3a3a3")
        self.ipm.configure(font="-family {Consolas} -size 10 -weight bold")
        self.ipm.configure(foreground="#919191")
        self.ipm.configure(highlightbackground="#4f4f4f")
        self.ipm.configure(highlightcolor="black")
        self.ipm.configure(insertbackground="#969696")
        self.ipm.configure(justify='center')
        self.ipm.configure(selectbackground="#c4c4c4")
        self.ipm.configure(selectforeground="black")
        self.ipm.configure(textvariable=SuperDuper_support.ipm)

        self.rctrpm = tk.Entry(self.output)
        self.rctrpm.place(relx=0.553, rely=0.193, height=19, relwidth=0.347
                , bordermode='ignore')
        self.rctrpm.configure(background="#000000")
        self.rctrpm.configure(disabledforeground="#a3a3a3")
        self.rctrpm.configure(font="-family {Consolas} -size 10 -weight bold")
        self.rctrpm.configure(foreground="#919191")
        self.rctrpm.configure(highlightbackground="#4f4f4f")
        self.rctrpm.configure(highlightcolor="black")
        self.rctrpm.configure(insertbackground="#969696")
        self.rctrpm.configure(justify='center')
        self.rctrpm.configure(selectbackground="#c4c4c4")
        self.rctrpm.configure(selectforeground="black")
        self.rctrpm.configure(textvariable=SuperDuper_support.rctipm)

        self.Label2_2 = tk.Label(self.output)
        self.Label2_2.place(relx=0.553, rely=0.116, height=11, width=54
                , bordermode='ignore')
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#000000")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#838383")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''RCT IPM''')

        self.rctipm = tk.Entry(self.output)
        self.rctipm.place(relx=0.553, rely=0.386, height=19, relwidth=0.347
                , bordermode='ignore')
        self.rctipm.configure(background="#000000")
        self.rctipm.configure(disabledforeground="#a3a3a3")
        self.rctipm.configure(font="-family {Consolas} -size 10 -weight bold")
        self.rctipm.configure(foreground="#919191")
        self.rctipm.configure(highlightbackground="#4f4f4f")
        self.rctipm.configure(highlightcolor="black")
        self.rctipm.configure(insertbackground="#969696")
        self.rctipm.configure(justify='center')
        self.rctipm.configure(selectbackground="#c4c4c4")
        self.rctipm.configure(selectforeground="black")
        self.rctipm.configure(textvariable=SuperDuper_support.rctipt)

        self.Label2_4 = tk.Label(self.output)
        self.Label2_4.place(relx=0.553, rely=0.309, height=11, width=54
                , bordermode='ignore')
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#000000")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#838383")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''RCT IPT''')

        self.stepoval = tk.Entry(self.output)
        self.stepoval.place(relx=0.1, rely=0.579, height=19, relwidth=0.353
                , bordermode='ignore')
        self.stepoval.configure(background="#000000")
        self.stepoval.configure(disabledforeground="#a3a3a3")
        self.stepoval.configure(font="-family {Consolas} -size 10 -weight bold")
        self.stepoval.configure(foreground="#919191")
        self.stepoval.configure(highlightbackground="#4f4f4f")
        self.stepoval.configure(highlightcolor="black")
        self.stepoval.configure(insertbackground="#969696")
        self.stepoval.configure(justify='center')
        self.stepoval.configure(selectbackground="#c4c4c4")
        self.stepoval.configure(selectforeground="black")
        self.stepoval.configure(textvariable=SuperDuper_support.stepovar)

        self.stepdval = tk.Entry(self.output)
        self.stepdval.place(relx=0.553, rely=0.579, height=19, relwidth=0.347
                , bordermode='ignore')
        self.stepdval.configure(background="#000000")
        self.stepdval.configure(disabledforeground="#a3a3a3")
        self.stepdval.configure(font="-family {Consolas} -size 10 -weight bold")
        self.stepdval.configure(foreground="#919191")
        self.stepdval.configure(highlightbackground="#4f4f4f")
        self.stepdval.configure(highlightcolor="black")
        self.stepdval.configure(insertbackground="#969696")
        self.stepdval.configure(justify='center')
        self.stepdval.configure(selectbackground="#c4c4c4")
        self.stepdval.configure(selectforeground="black")
        self.stepdval.configure(textvariable=SuperDuper_support.stepdvar)

        self.Label2_8 = tk.Label(self.output)
        self.Label2_8.place(relx=0.1, rely=0.502, height=11, width=54
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#000000")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(foreground="#838383")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(text='''Stepover''')

        self.Label2_9 = tk.Label(self.output)
        self.Label2_9.place(relx=0.553, rely=0.502, height=11, width=54
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(background="#000000")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(foreground="#838383")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(text='''Stepdown''')

        self.stepoval_10 = tk.Entry(self.output)
        self.stepoval_10.place(relx=0.1, rely=0.768, height=19, relwidth=0.353
                , bordermode='ignore')
        self.stepoval_10.configure(background="#000000")
        self.stepoval_10.configure(disabledforeground="#a3a3a3")
        self.stepoval_10.configure(font="-family {Consolas} -size 10 -weight bold")
        self.stepoval_10.configure(foreground="#919191")
        self.stepoval_10.configure(highlightbackground="#4f4f4f")
        self.stepoval_10.configure(highlightcolor="black")
        self.stepoval_10.configure(insertbackground="#969696")
        self.stepoval_10.configure(justify='center')
        self.stepoval_10.configure(selectbackground="#c4c4c4")
        self.stepoval_10.configure(selectforeground="black")

        self.Label2_1 = tk.Label(self.output)
        self.Label2_1.place(relx=0.1, rely=0.695, height=11, width=34
                , bordermode='ignore')
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#000000")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#838383")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''MRR''')

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.047, rely=0.432, height=21, width=34)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#000000")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#838383")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''IPT''')

if __name__ == '__main__':
    vp_start_gui()





